### ISSUE TITLE
Too many dependencies!!

### ISSUE THREAD

**Issue by YTMrSnipa** [NerdNu/DragonFight#1]
Hello there! There are wayyy too many dependency plugins required for this plugin to be run, can you do something about that? I first had to get BeastMaster, then worldedit, then libs disguises, then I can't even find "Entity Meta" anywhere.... This is just a lot of effort to run 1 plugin... So yeah man this may be a very cool plugin but can you reduce the number of other plugins it requires to run??

**Comment by totemo** [comment]
This is free software, offered "as is" using the most precious and scarce resource I have available to me: my time.

You are free to fork it and adapt it to meet your needs should you wish to do so.

I may in the future, at my own discretion, expend the hours necessary to better disentangle the software from the current dependencies. Some dependencies are obsoleted by improvements in the Bukkit API and server software and may be removed in the future. However, I have many competing demands upon my time and I have no intention of resolving this "problem" in a short time frame.
