### ISSUE TITLE
Seems to be incompatible with 1.16.5

### ISSUE THREAD

**Issue by deadkex** [NerdNu/DragonFight#2]
Hey there.
Would you mind taking a look into making it compatible with the newest version please?

**Comment by totemo** [comment]
I feel it's unlikely that there's anything directly incompatible within DragonFight, but I will investigate shortly. 1.16.5 didn't introduce any relevant API changes, AFAIK.

In the meantime, you should check that NerdNu/BeastMaster dependencies don't refuse to load on 1.16.5, particularly ProtocolLib, LibsDisguises and WorldGuard.

**Comment by totemo** [comment]
I've just re-tested with:

- Latest Paper git-Paper-529 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Latest LibsDisguises from https://www.spigotmc.org/resources/libs-disguises.32453/
- Latest stable ProtocolLib (LibsDisguises dependency) https://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/
- Current BeastMaster release https://github.com/NerdNu/BeastMaster/releases/tag/v2.14.0
- Current DragonFight release

I suggest if you are running all of these you file a detailed bug report with:

- Detailed server version information
- Plugin version information
- A console log showing exception information or screenshots of error messages

At one stage there were problems with LibsDiguises':

- Overly strict handling of disguises: https://github.com/libraryaddict/LibsDisguises/issues/525
- Handling of disguised projectiles:  https://github.com/libraryaddict/LibsDisguises/issues/526

**Comment by deadkex** [comment]
It worked, thank you. I think i had an Older Version of libsdisguises

**Comment by totemo** [comment]
Good to know.
